name: rk2
run-name: rk2
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: load_repository
        uses: actions/checkout@v4
      - name: Build
        run: cd solver_application && cmake -H. -B build && cmake --build build
      - name: Artefacts
        uses: actions/upload-artifact@v4
        with:
          name: example
          path: solver_application/build/equation
